a=10
b=3
print("Arithmetic operation")
print("Addition",a+b)
print("Subtraction",a-b)
print("Multiplication",a*b)
print("Division",a/b)
print("Modulus",a%b)
print("Floor Division",a//b)
print("Exponential",a^b)
print("----------------------")
print("Logical operation")
print("AND operation",a and b)
print("OR operation",a or b)
print("----------------------")
print("Comaprison operation")
print("a==b" ,a==b)
print("a>b" ,a>b)
print("a<b" ,a<b)
print("a>=b" ,a>=b)
print("a<=b" ,a<=b)
